// USER ACTIONS
export const USER_CLEAR_NAME = 'USER_CLEAR_NAME'
export const USER_CLEAR_GENDER = 'USER_CLEAR_GENDER'
export const USER_SET_NAME = 'USER_SET_NAME'
export const USER_SET_GENDER = 'USER_SET_GENDER'

// SUBJECT ACTIONS
export const SUBJECTS_REMOVE_SUBJECT = 'SUBJECTS_REMOVE_SUBJECT'
export const SUBJECTS_ADD_SUBJECT = 'SUBJECTS_ADD_SUBJECT'
export const SUBJECTS_UPDATE_SUBJECT = 'SUBJECTS_UPDATE_SUBJECT'
export const SUBJECTS_UPDATE_FAVORITE = 'SUBJECTS_UPDATE_FAVORITE'